name: MsTest Integration Tests

permissions:
  contents: read

on:
    pull_request:
        branches:
            - master
    workflow_dispatch:


jobs:
    build-and-test: 
        name: MsTest Integration Tests
        runs-on: ubuntu-latest
        env: 
            Parameter__DevServerPassword: testpassword
            Parameter__redisPassword: testpassword

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5
            
            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                global-json-file: './global.json'
                dotnet-version: 10.0

            - name: Restore Dependencies
              run: dotnet restore ./TMS.slnx
            
            - name: Build Solution
              run: dotnet build --no-restore

            - name: Run Tests
              run: dotnet test ./TMS.IntegrationTests/TMS.IntegrationTests.csproj --verbosity normal